// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qrejohvwbriuycfboajl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFyZWpvaHZ3YnJpdXljZmJvYWpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzOTc2OTUsImV4cCI6MjA1OTk3MzY5NX0.jFGtUDHPeC6BRuslcNcQ7I86AdvHxTt7IPziS9J_lcA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);